[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /DeepSpeed/tests
configfile: pytest.ini
plugins: timeout-2.3.1
[1mcollecting ... [0mcollected 5 items

checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe[4] [31mFAILED[0m[31m [ 20%][0m
checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-True] [31mFAILED[0m[31m [ 40%][0m
checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-False] [31mFAILED[0m[31m [ 60%][0m
checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-True] [31mFAILED[0m[31m [ 80%][0m
checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-False] [31mFAILED[0m[31m [100%][0m

=================================== FAILURES ===================================
[31m[1m___________________ TestMoECheckpoint.test_checkpoint_moe[4] ___________________[0m
Worker 0 killed by signal 11
----------------------------- Captured stdout call -----------------------------
[2024-04-10 06:27:06,167] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,173] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,186] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,191] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,194] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,204] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,212] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:06,223] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:07,045] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:07,046] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:07,063] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:07,063] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:07,094] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:07,095] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-10 06:27:07,095] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend ccl
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:07,110] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:07,110] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:07:(49664) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:07:(49664) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:07:(49664) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:07:(49664) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:07:(49664) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:08:(49663) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:08:(49663) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:08:(49663) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:08:(49663) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:08:(49663) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:08:(49665) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:08:(49665) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:08:(49665) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:08:(49665) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:08:(49665) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:08:(49662) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:08:(49662) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:08:(49662) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:08:(49662) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:08:(49662) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
----------------------------- Captured stderr call -----------------------------
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
[unset]: system msg for write_line failure : Bad file descriptor
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
[31m[1m____________ TestMoECheckpoint.test_checkpoint_moe_and_zero[4-True] ____________[0m
Worker 0 killed by signal 11
----------------------------- Captured stdout call -----------------------------
[2024-04-10 06:27:15,133] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,151] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,188] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,196] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,204] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,206] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,214] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:15,222] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:15,994] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:15,995] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-10 06:27:15,995] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend ccl
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:16,079] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:16,080] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:16:(51377) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:16:(51377) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:16:(51377) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:16:(51377) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:16:(51377) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:16,090] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:16,090] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:16:(51378) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:16:(51378) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:16:(51378) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:16:(51378) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:16:(51378) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:16,107] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:16,107] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:16:(51376) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:16:(51376) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:16:(51376) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:16:(51376) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:16:(51376) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:16:(51375) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:16:(51375) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:16:(51375) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:16:(51375) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:16:(51375) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
----------------------------- Captured stderr call -----------------------------
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
[31m[1m___________ TestMoECheckpoint.test_checkpoint_moe_and_zero[4-False] ____________[0m
Worker 0 killed by signal 11
----------------------------- Captured stdout call -----------------------------
[2024-04-10 06:27:23,470] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,480] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,484] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,488] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,490] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,498] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,503] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:23,506] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:24,385] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:24,385] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:24,432] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:24,433] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:24,461] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:24,461] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:24,474] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:24,474] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-10 06:27:24,474] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend ccl
2024:04:10-06:27:25:(53089) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:25:(53089) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:25:(53089) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:25:(53089) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:25:(53089) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:25:(53090) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:25:(53090) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:25:(53090) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:25:(53090) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:25:(53090) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:25:(53091) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:25:(53091) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:25:(53091) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:25:(53091) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:25:(53091) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:25:(53088) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:25:(53088) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:25:(53088) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:25:(53088) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:25:(53088) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
----------------------------- Captured stderr call -----------------------------
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
[unset]: Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
[unset]: system msg for write_line failure : Bad file descriptor
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
[31m[1m____________ TestMoECheckpoint.test_checkpoint_moe_and_zero[2-True] ____________[0m
Worker 0 killed by signal 11
----------------------------- Captured stdout call -----------------------------
[2024-04-10 06:27:32,537] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,556] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,599] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,609] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,611] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,618] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,627] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:32,629] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:33,410] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:33,412] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:33,516] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:33,516] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-10 06:27:33,516] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend ccl
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:33,531] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:33,531] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:33:(54803) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:33:(54803) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:33:(54803) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:33:(54803) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:33:(54803) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:33,548] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:33,548] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:33:(54804) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:33:(54804) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:33:(54804) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:33:(54804) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:33:(54804) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:34:(54802) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:34:(54802) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:34:(54802) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:34:(54802) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:34:(54802) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:34:(54801) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:34:(54801) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:34:(54801) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:34:(54801) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:34:(54801) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
----------------------------- Captured stderr call -----------------------------
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
[unset]: Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
[unset]: system msg for write_line failure : Bad file descriptor
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
[31m[1m___________ TestMoECheckpoint.test_checkpoint_moe_and_zero[2-False] ____________[0m
Worker 0 killed by signal 11
----------------------------- Captured stdout call -----------------------------
[2024-04-10 06:27:41,347] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,354] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,365] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,372] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,401] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,419] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,421] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2024-04-10 06:27:41,439] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:42,310] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:42,310] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:42,326] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:42,327] [INFO] [comm.py:637:init_distributed] cdb=None
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:42,343] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:42,343] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-10 06:27:42,343] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend ccl
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2024-04-10 06:27:42,358] [INFO] [comm.py:161:init_deepspeed_backend] Initialize ccl backend
[2024-04-10 06:27:42,358] [INFO] [comm.py:637:init_distributed] cdb=None
2024:04:10-06:27:42:(56516) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:42:(56516) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:42:(56516) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:42:(56516) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:42:(56516) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:43:(56515) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:43:(56515) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:43:(56515) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:43:(56515) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:43:(56515) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:43:(56517) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:43:(56517) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:43:(56517) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:43:(56517) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:43:(56517) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
2024:04:10-06:27:43:(56514) |CCL_WARN| did not find MPI-launcher specific variables, switch to ATL/OFI, to force enable ATL/MPI set CCL_ATL_TRANSPORT=mpi
2024:04:10-06:27:43:(56514) |CCL_WARN| could not get local_idx/count from environment variables, trying to get them from ATL
2024:04:10-06:27:43:(56514) |CCL_WARN| fallback to 'sockets' mode of ze exchange mechanism, to use CCL_ZE_IPC_EXHANGE=drmfd, set CCL_LOCAL_RANK/SIZE explicitly  or use process launcher
2024:04:10-06:27:43:(56514) |CCL_WARN| could not open the library: libfabric.so, error: libfabric.so: cannot open shared object file: No such file or directory
2024:04:10-06:27:43:(56514) |CCL_WARN| OFI transport was not initialized, fallback to MPI transport
----------------------------- Captured stderr call -----------------------------
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: [unset]: Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
system msg for write_line failure : Bad file descriptor
write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........: 
MPID_Init(1645)..............: 
MPIDI_OFI_mpi_init_hook(1574): 
(unknown)(): Unknown error class
system msg for write_line failure : Bad file descriptor
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
[33m=============================== warnings summary ===============================[0m
../../../usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13
  /usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
    warn(

../../../usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:28
  /usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import packaging  # type: ignore[attr-defined]

<string>:8
  <string>:8: PytestDeprecationWarning: A private pytest class or function was used.

unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe[4]
  /DeepSpeed/tests/conftest.py:47: UserWarning: Running test without verifying torch version, please provide an expected torch version with --torch_ver
    warnings.warn(

unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe[4]
  /DeepSpeed/tests/conftest.py:54: UserWarning: Running test without verifying cuda version, please provide an expected cuda version with --cuda_ver
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== slowest durations ===============================
9.18s call     unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-False]
9.09s call     unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-False]
8.95s call     unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe[4]
8.83s call     unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-True]
8.29s call     unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-True]

(10 durations < 1s hidden.  Use -vv to show these durations.)
[36m[1m=========================== short test summary info ============================[0m
[31mFAILED[0m checkpoint/test_moe_checkpoint.py::[1mTestMoECheckpoint::test_checkpoint_moe[4][0m - Failed: Worker 0 killed by signal 11
[31mFAILED[0m checkpoint/test_moe_checkpoint.py::[1mTestMoECheckpoint::test_checkpoint_moe_and_zero[4-True][0m - Failed: Worker 0 killed by signal 11
[31mFAILED[0m checkpoint/test_moe_checkpoint.py::[1mTestMoECheckpoint::test_checkpoint_moe_and_zero[4-False][0m - Failed: Worker 0 killed by signal 11
[31mFAILED[0m checkpoint/test_moe_checkpoint.py::[1mTestMoECheckpoint::test_checkpoint_moe_and_zero[2-True][0m - Failed: Worker 0 killed by signal 11
[31mFAILED[0m checkpoint/test_moe_checkpoint.py::[1mTestMoECheckpoint::test_checkpoint_moe_and_zero[2-False][0m - Failed: Worker 0 killed by signal 11
[31m======================== [31m[1m5 failed[0m, [33m5 warnings[0m[31m in 46.35s[0m[31m ========================[0m
